In [20]:
import pandas as pd
import numpy as np

In [21]:
df = pd.DataFrame([
       ['green', 'Chevrolet', 2017],
       ['blue', None, 2015], 
       ['yellow', 'Lexus', 2018],    
])
df.columns = ['color', 'make', 'year']

In [22]:
df.head()

color       make  year
0   green  Chevrolet  2017
1    blue       None  2015
2  yellow      Lexus  2018

In [23]:
df['make'] = df['make'].fillna('Unknown')

In [24]:
df.head()

color       make  year
0   green  Chevrolet  2017
1    blue    Unknown  2015
2  yellow      Lexus  2018

In [25]:
from sklearn.preprocessing import LabelEncoder
le_color = LabelEncoder()
le_make = LabelEncoder()
df['color_encoded'] = le_color.fit_transform(df.color)
df['make_encoded'] = le_make.fit_transform(df.make)

In [26]:
df.head()

color       make  year  color_encoded  make_encoded
0   green  Chevrolet  2017              1             0
1    blue    Unknown  2015              0             2
2  yellow      Lexus  2018              2             1

In [27]:
from sklearn.preprocessing import OneHotEncoder
color_ohe = OneHotEncoder()
make_ohe = OneHotEncoder()
X = color_ohe.fit_transform(df.color_encoded.values.reshape(-1,1)).toarray()
Xm = make_ohe.fit_transform(df.make_encoded.values.reshape(-1,1)).toarray()

/mnt/e/local/anaconda3/envs/azml2/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/mnt/e/local/anaconda3/envs/azml2/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can speci

In [28]:
dfOneHot = pd.DataFrame(X, columns = ["Color_"+str(int(i)) for i in range(X.shape[1])])
df = pd.concat([df, dfOneHot], axis=1)

dfOneHot = pd.DataFrame(Xm, columns = ["Make_"+str(int(i)) for i in range(X.shape[1])])
df = pd.concat([df, dfOneHot], axis=1)

In [29]:
df.head()

color       make  year  color_encoded  make_encoded  Color_0  Color_1  \
0   green  Chevrolet  2017              1             0      0.0      1.0   
1    blue    Unknown  2015              0             2      1.0      0.0   
2  yellow      Lexus  2018              2             1      0.0      0.0   

   Color_2  Make_0  Make_1  Make_2  
0      0.0     1.0     0.0     0.0  
1      0.0     0.0     0.0     1.0  
2      1.0     0.0     1.0     0.0

In [30]:
from sklearn.preprocessing import LabelBinarizer
color_lb = LabelBinarizer()
make_lb = LabelBinarizer()
X = color_lb.fit_transform(df.color.values)
Xm = make_lb.fit_transform(df.make.values)

In [31]:
X

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]])

In [32]:
Xm

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [33]:
W=color_lb.inverse_transform(X)
W

array(['green', 'blue', 'yellow'], dtype='<U6')

In [34]:
W = color_lb.transform(['unknown'])
W

array([[0, 0, 0]])

In [35]:
import pickle
pickle.dump(color_lb, open("color_lb.pickle", "wb"))

In [36]:
color_lb2 = pickle.load(open("color_lb.pickle", "rb"))

In [37]:
W=color_lb2.inverse_transform(X)
W

array(['green', 'blue', 'yellow'], dtype='<U6')